-- ============================================================
-- SALES SERVICE
-- V1 - Initial Schema
-- ============================================================


-- ============================================================
-- CUSTOMERS
-- ============================================================

CREATE TABLE customers
(
    id          UUID          NOT NULL,
    full_name   VARCHAR(150)  NOT NULL,
    notes       VARCHAR(1000),
    active      BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ   NOT NULL,
    updated_at  TIMESTAMPTZ   NOT NULL,

    CONSTRAINT pk_customers
        PRIMARY KEY (id)
);

CREATE INDEX idx_customers_full_name
    ON customers (full_name);


-- ============================================================
-- SALES
-- ============================================================

CREATE TABLE sales
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    seller_id               UUID           NOT NULL,
    customer_id             UUID           NOT NULL,
    customer_name_snapshot  VARCHAR(150)   NOT NULL,
    note                    VARCHAR(1000),
    stock_item_id           UUID           NOT NULL,

    quantity                NUMERIC(19,3)  NOT NULL,
    unit_price              NUMERIC(19,2)  NOT NULL,
    total_price             NUMERIC(19,2)  NOT NULL,

    status                  VARCHAR(40)    NOT NULL,
    failure_reason          VARCHAR(500),

    sold_at                 TIMESTAMPTZ    NOT NULL,
    created_at              TIMESTAMPTZ    NOT NULL,
    updated_at              TIMESTAMPTZ    NOT NULL,

    CONSTRAINT pk_sales
        PRIMARY KEY (id),

    CONSTRAINT chk_sales_status
        CHECK (
            status IN (
                'PENDING_STOCK_UPDATE',
                'COMPLETED',
                'FAILED'
            )
        ),

    CONSTRAINT chk_sales_quantity_positive
        CHECK (quantity > 0),

    CONSTRAINT chk_sales_unit_price_non_negative
        CHECK (unit_price >= 0),

    CONSTRAINT chk_sales_total_price_non_negative
        CHECK (total_price >= 0)
);

CREATE INDEX idx_sales_seller_id
    ON sales (seller_id);

CREATE INDEX idx_sales_stock_item_id
    ON sales (stock_item_id);

CREATE INDEX idx_sales_status
    ON sales (status);

CREATE INDEX idx_sales_created_at
    ON sales (created_at);

CREATE INDEX idx_sales_customer_id
    ON sales (customer_id);


-- ============================================================
-- PAYMENTS
-- ============================================================

CREATE TABLE payments
(
    id                    UUID          NOT NULL,
    sale_id               BIGINT        NOT NULL,

    amount                NUMERIC(19,2) NOT NULL,
    paid_at               TIMESTAMPTZ   NOT NULL,
    note                  VARCHAR(1000),

    recorded_by_user_id   UUID          NOT NULL,

    status                VARCHAR(20)   NOT NULL,

    void_reason           VARCHAR(500),
    voided_by_user_id     UUID,
    voided_at             TIMESTAMPTZ,

    created_at            TIMESTAMPTZ   NOT NULL,

    CONSTRAINT pk_payments
        PRIMARY KEY (id),

    CONSTRAINT fk_payments_sale
        FOREIGN KEY (sale_id)
        REFERENCES sales (id),

    CONSTRAINT chk_payments_status
        CHECK (
            status IN (
                'RECORDED',
                'VOIDED'
            )
        ),

    CONSTRAINT chk_payments_amount_positive
        CHECK (amount > 0)
);

CREATE INDEX idx_payments_sale_id
    ON payments (sale_id);

CREATE INDEX idx_payments_paid_at
    ON payments (paid_at);


-- ============================================================
-- PROCESSED EVENTS / INBOX
-- ============================================================

CREATE TABLE processed_events
(
    id              UUID          NOT NULL,
    event_id        UUID          NOT NULL,
    event_type      VARCHAR(100)  NOT NULL,
    consumer_name   VARCHAR(150)  NOT NULL,
    processed_at    TIMESTAMPTZ   NOT NULL,

    CONSTRAINT pk_processed_events
        PRIMARY KEY (id),

    CONSTRAINT uk_processed_event_consumer
        UNIQUE (event_id, consumer_name)
);

CREATE INDEX idx_processed_events_processed_at
    ON processed_events (processed_at);


-- ============================================================
-- OUTBOX EVENTS
-- ============================================================

CREATE TABLE outbox_events
(
    id              UUID          NOT NULL,
    event_id        UUID          NOT NULL,
    event_type      VARCHAR(100)  NOT NULL,

    aggregate_type  VARCHAR(100)  NOT NULL,
    aggregate_id    VARCHAR(100)  NOT NULL,

    exchange_name   VARCHAR(150)  NOT NULL,
    routing_key     VARCHAR(150)  NOT NULL,

    payload         TEXT          NOT NULL,

    status          VARCHAR(30)   NOT NULL,

    attempt_count   INTEGER       NOT NULL,

    last_error      VARCHAR(1000),

    created_at      TIMESTAMPTZ   NOT NULL,
    published_at    TIMESTAMPTZ,

    CONSTRAINT pk_outbox_events
        PRIMARY KEY (id),

    CONSTRAINT uk_outbox_event_id
        UNIQUE (event_id),

    CONSTRAINT chk_outbox_status
        CHECK (
            status IN (
                'PENDING',
                'PUBLISHED',
                'FAILED'
            )
        ),

    CONSTRAINT chk_outbox_attempt_count
        CHECK (attempt_count >= 0)
);

CREATE INDEX idx_outbox_status_created_at
    ON outbox_events (status, created_at);