spring:

  # ============================================================
  # FLYWAY TEST DATABASE
  #
  # Mevcut identity_db'ye dokunmuyoruz.
  # Tamamen boş identity_flyway_test DB kullanacağız.
  # ============================================================
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:identity_flyway_test}
    username: ${DB_USERNAME:identity_user}
    password: ${DB_PASSWORD:identity_pass}


  # ============================================================
  # JPA
  #
  # Flyway tabloları oluşturur.
  # Hibernate yalnızca entity-schema uyumunu doğrular.
  # ============================================================
  jpa:
    hibernate:
      ddl-auto: validate


  # ============================================================
  # FLYWAY
  #
  # application.yml içindeki false değerini override eder.
  # ============================================================
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true