-- ============================================================
-- PURCHASE SERVICE
-- V1 - INITIAL SCHEMA
-- ============================================================


-- ============================================================
-- PURCHASES
-- ============================================================

CREATE TABLE purchases
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,

    stock_item_id   UUID            NOT NULL,

    quantity        NUMERIC(19,3)   NOT NULL,
    unit_price      NUMERIC(19,4)   NOT NULL,

    supplier_name   VARCHAR(150)    NOT NULL,

    status          VARCHAR(40)     NOT NULL,

    purchased_at    TIMESTAMPTZ     NOT NULL,

    failure_reason  VARCHAR(500),

    created_at      TIMESTAMPTZ     NOT NULL,
    updated_at      TIMESTAMPTZ     NOT NULL,

    version         BIGINT          NOT NULL,

    CONSTRAINT pk_purchases
        PRIMARY KEY (id),

    CONSTRAINT chk_purchases_status
        CHECK (
            status IN (
                'PENDING_STOCK_UPDATE',
                'COMPLETED',
                'FAILED',
                'CANCELLED'
            )
        )
);

CREATE INDEX idx_purchases_stock_item_id
    ON purchases (stock_item_id);

CREATE INDEX idx_purchases_status
    ON purchases (status);

CREATE INDEX idx_purchases_created_at
    ON purchases (created_at);


-- ============================================================
-- PROCESSED EVENTS / INBOX
-- ============================================================

CREATE TABLE processed_events
(
    id              UUID          NOT NULL,

    event_id        UUID          NOT NULL,

    event_type      VARCHAR(100)  NOT NULL,

    consumer_name   VARCHAR(150)  NOT NULL,

    processed_at    TIMESTAMPTZ   NOT NULL,

    CONSTRAINT pk_processed_events
        PRIMARY KEY (id),

    CONSTRAINT uk_processed_event_consumer
        UNIQUE (
            consumer_name,
            event_id
        )
);

CREATE INDEX idx_processed_events_processed_at
    ON processed_events (processed_at);


-- ============================================================
-- OUTBOX EVENTS
-- ============================================================

CREATE TABLE outbox_events
(
    id               UUID          NOT NULL,

    event_id         UUID          NOT NULL,

    aggregate_type   VARCHAR(50)   NOT NULL,
    aggregate_id     VARCHAR(100)  NOT NULL,

    event_type       VARCHAR(100)  NOT NULL,
    event_version    INTEGER       NOT NULL,

    exchange_name    VARCHAR(150)  NOT NULL,
    routing_key      VARCHAR(150)  NOT NULL,

    payload           TEXT          NOT NULL,

    status            VARCHAR(30)   NOT NULL,

    attempt_count     INTEGER       NOT NULL,

    available_at      TIMESTAMPTZ   NOT NULL,

    created_at        TIMESTAMPTZ   NOT NULL,
    published_at      TIMESTAMPTZ,

    last_error        VARCHAR(1000),

    version           BIGINT,

    CONSTRAINT pk_outbox_events
        PRIMARY KEY (id),

    CONSTRAINT uk_outbox_events_event_id
        UNIQUE (event_id),

    CONSTRAINT chk_outbox_events_status
        CHECK (
            status IN (
                'PENDING',
                'PUBLISHED',
                'FAILED',
                'CANCELLED'
            )
        )
);

CREATE INDEX idx_outbox_events_status_available_at
    ON outbox_events (
        status,
        available_at
    );

CREATE INDEX idx_outbox_events_aggregate
    ON outbox_events (
        aggregate_type,
        aggregate_id
    );

CREATE INDEX idx_outbox_events_created_at
    ON outbox_events (created_at);