spring:

  # ============================================================
  # FLYWAY TEST DATABASE
  #
  # Mevcut inventory_db yerine tamamen boş test DB kullanılır.
  # ============================================================
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:inventory_flyway_test}
    username: ${DB_USERNAME:inventory_user}
    password: ${DB_PASSWORD:inventory_pass}


  # ============================================================
  # Hibernate tablo oluşturmayacak.
  #
  # Önce Flyway oluşturacak,
  # sonra Hibernate entity-schema uyumunu kontrol edecek.
  # ============================================================
  jpa:
    hibernate:
      ddl-auto: validate


  # ============================================================
  # application.yml'deki Flyway false değerini override ediyoruz.
  # ============================================================
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true